name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync project to server
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/milan/services/quickref

      - name: Build and restart container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/milan/services/quickref
            ls -la  # Debug : vérifier que docker-compose.yml est bien là
            docker compose -f docker-compose.yml up -d --build
          EOF
