name: Déploiement Quickref.me

on:
  push:
    branches:
      - main
    paths:
      - 'quickref/**'
      - '.github/workflows/deploy-quickref.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Ajout de la clé SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Synchronisation des fichiers avec le serveur
        run: |
          rsync -az -e "ssh -o StrictHostKeyChecking=no" ./quickref/ \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/milan/services/quickref

      - name: Rebuild + restart du container Docker
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/milan/services/quickref
            docker compose down
            docker compose up -d --build
          EOF
